### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by sponnify** [a10x/add-reaction#6]
TypeError: Cannot read property 'Permissions' of undefined
    at eval (betterdiscord://plugins/add_reaction.plugin.js:14:97)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)
    
    after relaunching i go the following: 

TypeError: Cannot read property 'Permissions' of undefined
    at eval (betterdiscord://plugins/add_reaction.plugin.js:14:97)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)

**Comment by FrostDelx** [comment]
@a10x pls fix
